### ISSUE TITLE
Should be able to edit target entitiy

### ISSUE THREAD

**Issue by kleag** [danovw/annotate_translation#4]
Currently, when an entity from automatic translation cannot be correctly aligned, it is set with a span covering all the target text. When it happens, the GUI displays [0, 0]. This is acceptable but unfortunately, it cannot be corrected without discarding also the source entity.

One should be able to edit a target entitiy without removing also the source one.

**Comment by danovw** [comment]
It seems to be a bit difficult to implement this feature on the current interface. I think there may be a compromise solution. 

Instead of clicking on an entity to delete it, a "delete entity" button could be added. Then, when click "add target entity", we can check if there is a selected item in the list, and if there is, we can get the index of the selected target entity, and then overwrite the old span with the new span. Finally, set the list to unselected state.

Some useful API includes `QListWidget.item(row)`, `QListWidget.currentRow()`, `QListWidget.setItemSelected(item, select)`, `QListWidgetItem.text()`.

**Comment by kleag** [comment]
Good idea. We could also keep the "Delete entity" behavior if there is no text selected. But if there is selected text in the target area and a element of the target entity list is clicked, then this entity is replaced by the selected text. I think this would be very intuitive. What do you think?

**Comment by danovw** [comment]
Sounds great!  And this way no additional interface modifications need to be introduced.

One thing to note is that it may be necessary to use `self.ui.target.setTextCursor(QTextCursor())` to reset the selected state of the target area after click "add target entity"

**Comment by kleag** [comment]
Hi @danovw , I don't have time to work on this feature but it would still be very useful :)

**Comment by danovw** [comment]
> Good idea. We could also keep the "Delete entity" behavior if there is no text selected. But if there is selected text in the target area and a element of the target entity list is clicked, then this entity is replaced by the selected text. I think this would be very intuitive. What do you think?

Thanks for your great idea! I have implemented this feature.

**Comment by kleag** [comment]
Yes, it works! Thanks a lot.
